"""Reviewed supplementary purchase documents and atomic stock carry-forward."""
import hashlib
import json
import re
from collections import defaultdict
from decimal import Decimal

try:
    from . import bk_import as bk
    from . import inventory_period_close as close
    from .purchase_summary_export import _key
    from .receipt_export import enrich_receipt_identity_rows, group_receipt_rows, RECEIPT_MAX_DAILY_AMOUNT
    from .invoice_inventory import invoice_stock_rows
except ImportError:
    import bk_import as bk
    import inventory_period_close as close
    from purchase_summary_export import _key
    from receipt_export import enrich_receipt_identity_rows, group_receipt_rows, RECEIPT_MAX_DAILY_AMOUNT
    from invoice_inventory import invoice_stock_rows


def rebuild_periods(conn, purchase_date):
    """Only rebuild openings generated by a recorded close, never manual balances."""
    periods=[]
    for opening in conn.execute("""SELECT DISTINCT source_id FROM inventory_transactions
        WHERE source_type='OPENING' AND status='posted' AND txn_date>? ORDER BY source_id""",(purchase_date,)):
        row=conn.execute("SELECT * FROM inventory_period_closures WHERE next_period=? AND status='closed'",(opening['source_id'],)).fetchone()
        if not row or row['target_hash']!=close._opening_hash(conn,opening['source_id']):
            raise ValueError('Tồn đầu kỳ '+opening['source_id']+' không khớp bản chuyển kỳ đã chốt. Cần đối chiếu trước khi nhập bổ sung; chưa ghi kho.')
        periods.append(dict(row))
    return sorted(periods,key=lambda r:r['period'])


def receipt_rows(conn, parsed):
    people=defaultdict(list)
    for p in conn.execute('SELECT * FROM people'):people[_key(p['name'])].append(dict(p))
    result=[]
    for r in parsed['rows']:
        matches=people[_key(r['sourceParty'])]
        if len(matches)!=1:
            raise ValueError('Người bán “'+r['sourceParty']+'” chưa có định danh duy nhất. Chọn tên trong danh mục người bán.')
        p=matches[0]
        result.append({'work_date':r['documentDate'],'seller':p['name'],'cccd':p['cccd'],
            'address':p['address'],'product_name':r['productName'],'unit':r['unit'],
            'quantity':r['qty'],'buy_price':r['unitCost'],'amount':r['amount'],
            'source_ref':r['sourceLine'],'reference':r['sourceReference'],'supplier':r['sourceParty']})
    result=enrich_receipt_identity_rows(conn,result)
    return result


def daily_check(conn, rows, existing_id):
    """Include other posted purchases; changing a reference cannot reset the cap."""
    people={_key(p['name']):str(p['cccd']) for p in conn.execute('SELECT name,cccd FROM people')}
    additions=defaultdict(Decimal);prior=defaultdict(Decimal)
    for r in rows:additions[(r['work_date'],r['cccd'])]+=Decimal(str(r['amount']))
    for r in conn.execute("""SELECT l.document_date,l.source_party,l.amount,l.document_id
        FROM bk_import_lines l JOIN bk_import_documents d ON d.id=l.document_id
        WHERE d.status='posted' AND l.document_date>=? AND l.document_date<=?""",
        (min(r['work_date'] for r in rows),max(r['work_date'] for r in rows))):
        if r['document_id']==existing_id:continue
        identity=people.get(_key(r['source_party']))
        prior[(r['document_date'],identity)]+=Decimal(str(r['amount']))
    # Document-only corrections supersede the original seller allocation.
    if conn.execute("SELECT 1 FROM sqlite_master WHERE name='purchase_seller_revisions'").fetchone():
        for saved in conn.execute('''SELECT s.*,a.document_id FROM purchase_seller_revisions s
            JOIN batch_bk_approvals a ON a.batch_id=s.batch_id
            JOIN bk_import_documents d ON d.id=a.document_id AND d.status='posted'
            WHERE s.revision=(SELECT MAX(t.revision) FROM purchase_seller_revisions t WHERE t.batch_id=s.batch_id)'''):
            if saved['document_id']==existing_id:continue
            for r in conn.execute('SELECT document_date,source_party,amount FROM bk_import_lines WHERE document_id=?',(saved['document_id'],)):
                prior[(r['document_date'],people.get(_key(r['source_party']))) ]-=Decimal(str(r['amount']))
            for r in json.loads(saved['rows_json']):prior[(r['work_date'],r['cccd'])]+=Decimal(str(r['amount']))
    for key,value in additions.items():
        if prior[key]+value>RECEIPT_MAX_DAILY_AMOUNT:
            name=next(r['seller'] for r in rows if (r['work_date'],r['cccd'])==key)
            raise ValueError(f'{name}, ngày {key[0]}: đã ghi {prior[key]:,.0f}đ + bổ sung {value:,.0f}đ vượt hạn mức 5.000.000đ. Giảm lượng chọn; ngày mua thực tế giữ nguyên.')


def prepare(conn, blob, start, end):
    parsed=bk.parse_bk_preview(conn,blob,allow_generated_rebuild=True)
    if not parsed['canConfirm']:
        errors=['Dòng '+str(r['sourceRow'])+': '+'; '.join(r['errors']) for r in parsed['rows'] if r['errors']]
        raise ValueError('Chưa đủ dữ liệu lập bộ bảng kê: '+' | '.join(errors[:8]))
    dates={r['documentDate'] for r in parsed['rows']}
    source_state={}
    if any(not start<=day<=end for day in dates):raise ValueError('Ngày mua thực tế phải nằm trong kỳ đang chọn.')
    if not parsed['alreadyPosted'] and any('[TDP-SOURCE:' in r['note'] for r in parsed['rows']):
        try:
            from .bk_purchase_sources import purchase_sources
        except ImportError:
            from bk_purchase_sources import purchase_sources
        available,_=purchase_sources(conn,start,end,{r['productCode'] for r in parsed['rows']})
        bykey={r['source_key']:(code,r) for code,items in available.items() for r in items}
        quantities=defaultdict(float)
        for r in parsed['rows']:
            match=re.search(r'\[TDP-SOURCE:([^\]]+)\]',r['note'])
            if not match:continue
            key=match.group(1);quantities[key]+=float(r['qty'])
            source=bykey.get(key)
            if not source or source[0]!=r['productCode'] or quantities[key]>float(source[1]['purchase_qty'])+0.000001:
                raise ValueError('Nguồn mua đã bổ sung hoặc lượng chọn vượt lượng mua còn lại. Bấm Xem hàng tồn âm để đối chiếu lại; thông tin đang nhập được giữ lại.')
            source_state[key]=source
        stock={r['product_code']:r['closing_qty'] for r in invoice_stock_rows(conn,as_of=end,include_zero=True)}
        totals=defaultdict(float)
        for r in parsed['rows']:totals[r['productCode']]+=float(r['qty'])
        for code,qty in totals.items():
            if qty>max(0,-stock.get(code,0))+0.000001:
                raise ValueError(f'{code}: Lượng mua bổ sung vượt lượng còn thiếu cuối kỳ. Bấm Xem hàng tồn âm để đối chiếu lại; thông tin đang nhập được giữ lại.')
    receipts=receipt_rows(conn,parsed)
    daily_check(conn,receipts,parsed['existingDocumentId'])
    group_receipt_rows(receipts)
    periods=[] if parsed['alreadyPosted'] else rebuild_periods(conn,min(dates))
    database_hash=bk._database_state_hash(conn,parsed['rows'])
    # Immutable events and source/target openings participate in optimistic locking.
    inventory=[tuple(r) for r in conn.execute('''SELECT id,product_code,txn_date,qty_delta,unit_cost,status
        FROM invoice_inventory_effective_ledger WHERE txn_date>=? ORDER BY id''',(min(dates),))]
    openings=[tuple(r) for r in conn.execute("SELECT * FROM inventory_transactions WHERE source_type='OPENING' ORDER BY id")]
    state=bk._hash_json([parsed['contentHash'],receipts,periods,database_hash,inventory,openings,source_state])
    return {'parsed':parsed,'receipts':receipts,'periods':periods,'state_hash':state,
            'database_state_hash':database_hash,'blob':blob,'start':start,'end':end}


def post(conn, prepared, actor, timestamp, audit_event):
    actor=str(actor or '').strip()
    if not actor or len(actor)>100:raise ValueError('Điền tên người xác nhận nhập kho (tối đa 100 ký tự).')
    current=prepare(conn,prepared['blob'],prepared['start'],prepared['end'])
    p=current['parsed']
    if not p['alreadyPosted'] and current['state_hash']!=prepared['state_hash']:
        raise ValueError('Nguồn hàng hoặc tồn kho vừa thay đổi. Bấm xem và kiểm tra lại trước khi nhập.')
    periods=current['periods']
    for period in reversed(periods):
        close.reopen_inventory_period(conn,period['period'],timestamp=timestamp,actor=actor+' · BK bổ sung')
    pending={'content_hash':p['contentHash'],'source_hash':hashlib.sha256(prepared['blob']).hexdigest().upper(),
        'filename':'BK_BO_SUNG_'+prepared['start']+'_'+prepared['end']+'.xlsx',
        'rows':p['rows'],'database_state_hash':current['database_state_hash']}
    result=bk._post_pending(conn,pending,timestamp,audit_event)
    for period in periods:
        preview=close.inventory_period_close_preview(conn,period['period'])
        if not preview['can_close']:
            names=', '.join(r['product_code']+' · '+r['product_name'] for r in preview['blocking_items'])
            error=ValueError('Chưa nhập kho: chưa cập nhật được tồn chuyển tháng '+period['period']+'. '+
                             (('Cần đối chiếu '+names+'. ') if names else '')+'; '.join(preview['issues'])+
                             '. Dữ liệu của bộ này chưa được ghi; các ô đã nhập vẫn được giữ lại.')
            error.stock_review={'period':period['period'],'items':preview['blocking_items']}
            raise error
        close.close_inventory_period(conn,period['period'],expected_source_hash=preview['source_hash'],
            expected_target_hash=preview['target_hash'],timestamp=timestamp,actor=actor+' · BK bổ sung')
    codes={r['productCode'] for r in p['rows']}
    stock=[{'product_code':r['product_code'],'closing_qty':round(r['closing_qty'],6)}
        for r in invoice_stock_rows(conn,as_of=prepared['end'],include_zero=True) if r['product_code'] in codes]
    audit_event(conn,'bk_supplement.confirm',entity_type='bk_import_document',entity_id=str(result['documentId']),
        metadata={'actor':actor,'rebuilt_periods':[r['period'] for r in periods],'idempotent':result['idempotent']})
    return {**result,'stock':stock,'stock_date':prepared['end'],'rebuilt_periods':[r['period'] for r in periods]}
