const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const {chromium}=require(process.env.TDP_PLAYWRIGHT_PATH || 'C:/Users/DELL/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:18802',out=path.join(__dirname,'exports','output_stock_remap_test');
(async()=>{
 fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1500,height:1000}});page.setDefaultTimeout(20000);
 const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(r.request().method()==='POST')writes.push(u.pathname);return r.continue();});
 try{
  await page.goto(base);await page.locator('#batchSelect option').waitFor({state:'attached'});
  await page.locator('#nav [data-view=documents]').click();
  await page.locator('.invoice-readiness').waitFor();
  await page.getByText(/KKKNT vẫn được lập bảng kê dù tồn âm/).waitFor();
  assert.equal(await page.locator('#outgoing-stock-blocks').count(),0);
  const create=page.locator('[data-action=create-outgoing-drafts]').first();
  await create.click();
  const zip=page.waitForEvent('download');await page.locator('[data-action=download-document]').filter({hasText:'Tải ZIP hóa đơn'}).first().click();
  await (await zip).saveAs(path.join(out,'KKKNT_am_van_tai_duoc.zip'));
  await page.locator('#nav [data-view=inventory]').click();
  await page.locator('#inventoryFrom').fill('2026-08-01');await page.locator('#inventoryTo').fill('2026-08-31');await page.locator('#inventoryTo').blur();
  await page.locator('[data-action=open-inventory-close]').click();
  await page.locator('[data-close-remap]').waitFor();
  assert.equal(await page.locator('[data-action=close-inventory-month]').count(),0);
  await page.locator('[data-close-remap]').click();
  const download=page.waitForEvent('download');await page.locator('[data-remap-download]').click();
  const file=path.join(out,'Doi_ma.xlsx');await (await download).saveAs(file);
  cp.execFileSync('python',['-c',"import sys;from openpyxl import load_workbook;p=sys.argv[1];w=load_workbook(p);s=w['Doi ma xuat kho'];assert s['Q4'].value=='Mã nội bộ mới';assert s.max_row==5;assert '1 dòng cần xử lý / 1 mã hàng' in s['L1'].value;s['Q5']='REMAP-B';s['R5']='Hàng nhận';w.save(p)",file]);
  const bad=path.join(out,'Sai_ten.xlsx');
  cp.execFileSync('python',['-c',"import sys;from openpyxl import load_workbook;w=load_workbook(sys.argv[1]);w['Doi ma xuat kho']['R5']='Tên không khớp';w.save(sys.argv[2])",file,bad]);
  await page.locator('[data-remap-file]').setInputFiles(bad);
  await page.getByText(/Tên đúng của mã REMAP-B: Hàng nhận/).waitFor();
  assert.equal(await page.locator('[data-remap-confirm]').count(),0);
  assert((await page.locator('[data-remap-message]').innerText()).includes('Hàng số 5 trong Excel · HH-01 · Hàng hóa 01'));
  await page.screenshot({path:path.join(out,'00_loi_co_ten_hang.png'),fullPage:true});
  await page.locator('[data-remap-file]').setInputFiles(file);
  await page.locator('[data-remap-confirm]').waitFor();
  assert((await page.locator('[data-remap-preview]').innerText()).includes('REMAP-B'));
  assert((await page.locator('[data-remap-preview]').innerText()).includes('→ Sang'));
  assert((await page.locator('[data-remap-preview]').innerText()).includes('4 kg → 4 Bịch'));
  assert((await page.locator('[data-remap-preview]').innerText()).includes('6 Bịch'));
  await page.screenshot({path:path.join(out,'01_xem_truoc_doi_ma.png'),fullPage:true});
  await page.locator('[data-remap-confirm] input').fill('Kiểm thử');
  await page.locator('[data-remap-confirm] button').click();
  await page.getByText('Đã đổi 1 dòng nội bộ và tính lại tồn. Hóa đơn gốc giữ nguyên.',{exact:true}).waitFor();
  await page.locator('[data-remap-close]').click();
  await page.locator('[data-action=open-inventory-close]').click();
  await page.locator('[data-action=close-inventory-month]').waitFor();
  await page.getByText(/Có 1 mã KKKNT âm/).waitFor();
  await page.locator('#inventoryCloseActor').fill('Kiểm thử');
  await page.screenshot({path:path.join(out,'02_kkknt_duoc_chuyen_am.png'),fullPage:true});
  await page.locator('[data-action=close-inventory-month]').click();
  await page.locator('[data-action=reopen-inventory-month]').waitFor();
  const close=await (await page.request.get(base+'/api/inventory/month-close/preview?period=2026-08')).json();
  assert.equal(close.status,'closed');assert.equal(close.kkknt_negative_count,1);
  await page.screenshot({path:path.join(out,'03_da_chuyen_thang.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({ok:true,excel_round_trip:true,kkknt_negative_export:true,month_closed:true,writes,errors},null,2));
  console.log('PASS Excel remap, negative KKKNT export and month closing');
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
