'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');

async function main() {
  const page = await fetch('http://127.0.0.1:19315/json/new?about:blank', {method:'PUT'}).then(r => r.json());
  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let seq=0; const pending=new Map(), errors=[];
  ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails);if(pending.has(msg.id)){const [yes,no]=pending.get(msg.id);pending.delete(msg.id);msg.error?no(Error(msg.error.message)):yes(msg.result);}};
  const call=(method,params={})=>new Promise((yes,no)=>{const id=++seq;pending.set(id,[yes,no]);ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const wait=async expression=>{const until=Date.now()+20000;while(Date.now()<until){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timeout: '+expression);};
  const click=async selector=>{await wait(`document.querySelector(${JSON.stringify(selector)})`);await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);};
  const set=async(selector,value,type='input')=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event(${JSON.stringify(type)},{bubbles:true}));})()`);
  try {
    await call('Runtime.enable');await call('Page.enable');
    await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:'D:/TDP_ROUND3/downloads'});
    await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
    await call('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.removeItem("tdp.receivableFilters");localStorage.removeItem("tdp.payableFilters");window.confirm=()=>true;window.prompt=(m)=>m.includes("Tên")?"Người kiểm thử":"Nhập nhầm";`});
    await call('Page.navigate',{url:'http://127.0.0.1:18805'});
    await wait(`document.querySelector('[data-view="reports"]')&&!document.querySelector('.loading-panel')`);
    await click('[data-view="reports"]');
    await wait(`document.querySelector('#monthlyReportTable tbody tr')`);
    assert.match(await evaluate(`document.querySelector('#monthlyReportTable').textContent`),/K2/);
    await set('#reportPeriod','2026-08','change');
    await wait(`document.querySelector('#monthlyReportTable') && !document.querySelector('.loading-inline')`);
    const empty=await evaluate(`document.querySelector('#monthlyReportTable tbody tr:last-child td:last-child').textContent`);
    assert.match(empty,/^0/);
    await set('#reportPeriod','2026-09','change');
    await wait(`document.querySelector('#monthlyReportTable') && !document.querySelector('.loading-inline')`);
    assert.equal(await evaluate(`performance.getEntriesByType('resource').filter(r=>r.name.includes('/export')).length`),0,'Viewing never downloads Excel');
    await evaluate(`window.__fetchBeforeRound3=window.fetch;window.fetch=async(...args)=>{const u=String(args[0]);if(u.includes('/api/reports/monthly?period=2026-08')){const r=await window.__fetchBeforeRound3(...args);await new Promise(r=>setTimeout(r,600));return r;}return window.__fetchBeforeRound3(...args);};`);
    await set('#reportPeriod','2026-08','change');await set('#reportPeriod','2026-09','change');
    await wait(`document.querySelector('#monthlyReportTable') && !document.querySelector('.loading-inline')`);
    await evaluate(`new Promise(r=>setTimeout(r,750))`);
    assert.doesNotMatch(await evaluate(`document.querySelector('#monthlyReportTable tbody tr:last-child td:last-child').textContent`),/^0/,'Late old-month response cannot replace current month');
    await evaluate(`window.fetch=async(...args)=>String(args[0]).includes('/api/reports/monthly?period=2026-08')?new Response(JSON.stringify({error:'Lỗi thử nghiệm'}),{status:500,headers:{'Content-Type':'application/json'}}):window.__fetchBeforeRound3(...args);`);
    await set('#reportPeriod','2026-08','change');await wait(`document.querySelector('.error-summary')`);
    assert.equal(await evaluate(`!!document.querySelector('#monthlyReportTable')`),false,'Failure cannot present old money as current');
    await evaluate(`window.fetch=window.__fetchBeforeRound3`);await set('#reportPeriod','2026-09','change');
    await wait(`document.querySelector('#monthlyReportTable') && !document.querySelector('.loading-inline')`);
    fs.writeFileSync('D:/TDP_ROUND3/report-browser.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
    await click('[data-view="debts"]');
    assert.equal(await evaluate(`document.querySelectorAll('.debt-menu-card').length`),3);
    await click('[data-section="receivable-kitchen"]');
    await wait(`document.querySelector('.receivable-ledger-table tbody')?.rows.length===70 && !document.querySelector('.loading-inline')`);
    const footer=await evaluate(`document.querySelector('.receivable-ledger-table tfoot').textContent`);
    assert.match(footer,/kg/);assert.match(footer,/cái/);
    const sticky=await evaluate(`(()=>{const box=document.querySelector('.receivable-ledger-table');box.scrollTop=500;box.scrollLeft=200;const th=box.querySelector('th');return {position:getComputedStyle(th).position,top:Math.abs(th.getBoundingClientRect().top-box.getBoundingClientRect().top),horizontal:box.scrollWidth>box.clientWidth,color:getComputedStyle(th).color};})()`);
    assert.equal(sticky.position,'sticky');assert.ok(sticky.top<5);assert.ok(sticky.horizontal);assert.ok(await evaluate(`(()=>{const th=document.querySelector('.receivable-ledger-table th');const lum=color=>{const v=color.match(/\\d+/g).slice(0,3).map(n=>{n=Number(n)/255;return n<=0.04045?n/12.92:Math.pow((n+0.055)/1.055,2.4)});return v[0]*0.2126+v[1]*0.7152+v[2]*0.0722};const style=getComputedStyle(th);let node=th,bg=style.backgroundColor;while(bg==='rgba(0, 0, 0, 0)'&&node.parentElement){node=node.parentElement;bg=getComputedStyle(node).backgroundColor;}const a=lum(style.color),b=lum(bg);return (Math.max(a,b)+0.05)/(Math.min(a,b)+0.05)>=4.5;})()`),'Header text must remain readable against its current background');
    await evaluate(`window.fetch=(...args)=>{if(String(args[0]).includes('/api/debts/receivables/ledger?'))args[0]=String(args[0]).replace('limit=5000','limit=10');return window.__fetchBeforeRound3(...args);};`);
    await click('#receivableFilterForm [type="submit"]');
    await wait(`document.querySelector('.receivable-ledger-table tbody')?.rows.length===10`);
    const page1=await evaluate(`document.querySelector('.receivable-ledger-table tbody').textContent`);
    await click('[data-action="ledger-page"][data-kind="receivable"][data-offset="10"]');
    await wait(`document.querySelector('.ledger-pager').textContent.includes('11–20')`);
    assert.notEqual(await evaluate(`document.querySelector('.receivable-ledger-table tbody').textContent`),page1);
    assert.equal(await evaluate(`document.querySelector('.receivable-ledger-table tfoot').textContent`),footer,'Totals include all filtered pages');
    await evaluate(`window.fetch=window.__fetchBeforeRound3`);
    await set('#receivableContractor','C1','change');await set('#receivableKitchen','K2','change');
    await click('#receivableFilterForm [type="submit"]');await wait(`document.querySelector('.receivable-ledger-table .empty')`);
    assert.match(await evaluate(`document.querySelector('#receivableFilteredExport').href`),/kitchen=K2/);
    await set('#receivableKitchen','K1','change');await click('#receivableFilterForm [type="submit"]');
    await wait(`document.querySelector('.receivable-ledger-table tbody')?.rows.length===70`);
    fs.writeFileSync('D:/TDP_ROUND3/receivable-browser.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
    await click('[data-action="back-debt-overview"]');await click('[data-section="receivable-total"]');
    await wait(`document.querySelector('#receiptForm') && !document.querySelector('.loading-inline')`);
    assert.equal(await evaluate(`document.querySelectorAll('[data-action="delete-payment"]').length`),0);
    await set('#receiptForm [name="actor"]','Người kiểm thử');await set('#receiptForm [name="party_code"]','C1');
    await set('#receiptForm [name="amount"]','100');await set('#receiptForm [name="payment_date"]','2026-09-05','change');
    await click('#receiptForm [type="submit"]');await wait(`document.querySelector('[data-action="reverse-receipt"]')`);
    await click('[data-action="reverse-receipt"]');
    await wait(`!document.querySelector('[data-action="reverse-receipt"]') && document.querySelector('#content').textContent.includes('Đã hoàn tác')`);
    await click('[data-action="back-debt-overview"]');await click('[data-section="payable"]');
    await wait(`document.querySelectorAll('.payable-line-select').length===70 && !document.querySelector('.loading-inline')`);
    assert.equal(await evaluate(`document.querySelector('#payableStatus').value`),'outstanding');
    assert.match(await evaluate(`document.querySelector('a[href*="/api/debts/payables/export"]').href`),/status=open%2Cpartially_paid/);
    const amount=await evaluate(`document.querySelector('.payable-line-select').dataset.remaining`);
    await click('.payable-line-select');await set('.payable-allocation-input',amount);
    await set('#payablePaymentForm [name="actor"]','Người kiểm thử');await click('#payablePaymentSubmit');
    await wait(`document.querySelector('[data-action="reverse-payable-payment"]') && document.querySelectorAll('.payable-line-select').length===69`);
    await click('[data-action="reverse-payable-payment"]');await wait(`document.querySelectorAll('.payable-line-select').length===70`);
    fs.writeFileSync('D:/TDP_ROUND3/payable-browser.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
    await call('Emulation.setDeviceMetricsOverride',{width:1024,height:800,deviceScaleFactor:1,mobile:false});
    assert.ok(await evaluate(`document.documentElement.scrollWidth<=window.innerWidth+2`),'No page spill');
    assert.equal(errors.length,0,JSON.stringify(errors));
    console.log('PASS round3: reports, filters, unit totals, sticky/scroll tables, receipt/payment reversal, 1440/1024 layouts');
  } catch(error) {
    console.log('Browser failure details', await evaluate(`({text:document.querySelector('#content')?.textContent.slice(-1600),contractor:document.querySelector('#receivableContractor')?.value,kitchen:document.querySelector('#receivableKitchen')?.value,requests:performance.getEntriesByType('resource').slice(-12).map(r=>r.name)})`));
    throw error;
  } finally { await call('Page.close');ws.close(); }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
