const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.TDP_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}});
 const base=process.env.TDP_INVOICE_TEST_URL,errors=[],writes=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')writes.push(new URL(r.url()).pathname);});
 const get=async p=>(await page.request.get(base+p)).json();
 const api='/api/invoice-workbench/invoices?invoice_type=output&from=2026-08-01&to=2026-08-31';
 try{
  await page.addInitScript(()=>localStorage.setItem('tdp.invoiceWorkbenchFilters',JSON.stringify({direction:'output',date_from:'2026-08-01',date_to:'2026-08-31',status:'all',line_filter:'all',scope_version:2})));
  await page.goto(base);await page.locator('.loading-panel').waitFor({state:'detached'});
  await page.locator('[data-view=msmi]').click();await page.locator('#invoice-list-count').waitFor();
  const ids=(await get('/fixture/ids')).output_name_lines,before=await get(api);
  const cell=key=>page.locator('#invoice-line-output-'+ids[key]+' td').nth(2);
  assert.equal(await cell('blank').innerText(),'Chưa ghép');assert.equal(await cell('coded').innerText(),'R1-KG');
  assert.match(await cell('blank').getAttribute('title'),/Không có/);
  const blocked=page.locator('#invoice-line-output-'+ids.blocked);
  assert.equal(await cell('blocked').innerText(),'Chờ kiểm tra HĐ');
  assert.match(await blocked.innerText(),/Hóa đơn cần kiểm tra/);
  assert.match(await blocked.innerText(),/1.938.000 đ.*2.058.000 đ/);
  assert.match(await blocked.innerText(),/Mã trên hóa đơn gốc: R1-KG/);
  assert.equal(await blocked.locator('.invoice-mapping-input').count(),0);
  const unit=page.locator('#invoice-line-output-'+ids.unit_review);
  assert.match(await unit.innerText(),/Đã khớp mã/);
  assert.equal(await unit.locator('.invoice-draft-factor').count(),0);
  const unitSave=page.waitForResponse(r=>r.url().endsWith('/'+ids.unit_review+'/mapping')&&r.status()===200);
  await unit.locator('[data-action=save-invoice-mapping]').click();await unitSave;
  await page.waitForFunction(id=>document.querySelector('#invoice-line-output-'+id+' .invoice-mapping-state')?.textContent==='Đã khớp mã.',ids.unit_review);
  const unitSaved=(await get(api)).lines.find(r=>r.id===ids.unit_review);
  assert.equal(await page.locator('.invoice-output-conversion, .invoice-output-table .invoice-draft-factor').count(),0);
  assert.equal(unitSaved.mapping_status,'mapped');assert.equal(unitSaved.stock_qty,5500);assert.equal(unitSaved.amount,7150000);assert.equal(unitSaved.issue,'');
  const financial=page.locator('#invoice-line-output-'+ids.amount_review);
  assert.equal(await financial.locator('.invoice-mapping-input').count(),1);
  await financial.locator('.invoice-mapping-input').fill('R1-KG');
  await page.locator('#msmiProductOptions [data-product-code="R1-KG"]').click();
  const financialSave=page.waitForResponse(r=>r.url().endsWith('/'+ids.amount_review+'/mapping')&&r.status()===200);
  await financial.locator('[data-action=save-invoice-mapping]').click();await financialSave;
  await page.waitForFunction(id=>document.querySelector('#invoice-line-output-'+id+' .invoice-mapping-state')?.textContent==='Đã khớp mã.',ids.amount_review);
  assert.equal(await financial.getAttribute('data-issue'),'0');
  assert.notEqual(await financial.locator('td').first().evaluate(e=>getComputedStyle(e).color),'rgb(163, 35, 35)');
  assert(!/lệch tiền/.test(await financial.innerText()));
  assert.equal(await unit.getAttribute('data-issue'),'0');
  assert.equal(await financial.locator('.invoice-source-review-note').count(),0);
  const reviews=page.locator('.invoice-amount-reviews');
  assert.match(await reviews.locator('summary').innerText(),/1 hóa đơn cần đối chiếu tiền/);
  await reviews.locator('summary').click();
  assert.match(await reviews.innerText(),/100.000 đ[\s\S]*120.000 đ[\s\S]*20.000 đ/);
  const financialInvoice=(await get(api)).lines.find(r=>r.id===ids.amount_review).invoice_id;
  assert.equal(await reviews.locator('[data-amount-review="'+financialInvoice+'"] td[rowspan]').count(),1);
  await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'invoice-amount-breakdown.png')});
  await reviews.locator('summary').click();
  await page.locator('.invoice-lines-card .tdp-open-sheet').click();
  await page.locator('[data-action=filter-invoice-issues]').click();
  await page.waitForFunction(()=>document.querySelector('[data-action=filter-invoice-issues]')?.getAttribute('aria-pressed')==='true');
  await page.locator('.invoice-mapping-fullscreen-bar').waitFor({state:'visible'});
  assert.equal(await financial.count(),0);assert.equal(await unit.count(),0);
  assert.equal(await page.locator('.invoice-lines-scroll tbody tr[data-issue="0"]').count(),0);
  assert.equal(await reviews.count(),1);
  assert.equal(await blocked.getAttribute('data-issue'),'1');
  assert.equal(await blocked.locator('td').first().evaluate(e=>getComputedStyle(e).color),'rgb(163, 35, 35)');
  await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'only-red-fullscreen.png')});
  await page.locator('[data-action=filter-invoice-issues]').click();
  await page.waitForFunction(()=>document.querySelector('[data-action=filter-invoice-issues]')?.getAttribute('aria-pressed')==='false');
  assert.equal(await financial.getAttribute('data-issue'),'0');
  await financial.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'financial-review-editable.png')});
  await unit.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'unit-review-saved.png')});
  const collision=page.locator('#invoice-line-output-'+ids.collision);
  assert.match(await collision.innerText(),/Tên không khớp/);
  assert.match(await collision.innerText(),/Mã kho: R1-KG/);
  await collision.locator('[data-action=review-invoice-identity]').click();
  const identityDialog=page.locator('.invoice-identity-dialog');
  await identityDialog.waitFor({state:'visible'});
  assert.match(await identityDialog.innerText(),/Bánh đa đỏ ướt/);
  assert.match(await identityDialog.innerText(),/R1-KG.*Hàng kiểm thử kg/);
  await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'identity-comparison.png')});
  await identityDialog.locator('[data-identity-cancel]').click();
  await identityDialog.waitFor({state:'detached'});
  await page.waitForFunction(id=>!document.querySelector('#invoice-line-output-'+id+' [data-action=review-invoice-identity]').disabled,ids.collision);
  assert.match(await collision.innerText(),/Tên không khớp/);
  await collision.locator('[data-action=save-invoice-mapping]').click();
  await identityDialog.waitFor({state:'visible'});await page.keyboard.press('Escape');
  await page.waitForFunction(id=>!document.querySelector('#invoice-line-output-'+id+' [data-action=save-invoice-mapping]').disabled,ids.collision);
  assert.equal((await get(api)).lines.find(r=>r.id===ids.collision).product_code,'R1-KG');
  const confirmedVariant=page.locator('#invoice-line-output-'+ids.confirmed_variant);
  await confirmedVariant.locator('[data-action=save-invoice-mapping]').click();
  await identityDialog.waitFor({state:'visible'});
  const confirmSaved=page.waitForResponse(r=>r.url().endsWith('/'+ids.confirmed_variant+'/mapping')&&r.status()===200);
  await identityDialog.locator('[data-identity-confirm]').click();await confirmSaved;
  await page.waitForFunction(id=>document.querySelector('#invoice-line-output-'+id)?.getAttribute('data-issue')==='0',ids.confirmed_variant);
  assert.equal(await confirmedVariant.locator('.invoice-identity-review').count(),0);
  assert.equal(await confirmedVariant.locator('.invoice-draft-factor').count(),0);
  assert.match(await confirmedVariant.innerText(),/Đã khớp mã/);
  assert.notEqual(await confirmedVariant.locator('td').first().evaluate(e=>getComputedStyle(e).color),'rgb(163, 35, 35)');
  const collisionInput=collision.locator('.invoice-mapping-input');await collisionInput.fill('G000007');
  await page.locator('#msmiProductOptions [data-product-code="G000007"]').click();
  assert.equal(await collision.locator('.invoice-identity-review').isVisible(),false);
  const correction=page.waitForResponse(r=>r.url().endsWith('/'+ids.collision+'/mapping')&&r.status()===200);
  await collision.locator('[data-action=save-invoice-mapping]').click();await correction;
  await page.waitForFunction(id=>document.querySelector('#invoice-line-output-'+id+' td:nth-child(3)')?.textContent==='G000007',ids.collision);
  assert(!/Tên không khớp/.test(await collision.innerText()));assert.match(await collision.innerText(),/Mã kho: G000007/);
  const taxRows=ids.tax_adjustment_lines.map(id=>page.locator('#invoice-line-output-'+id));
  await taxRows[0].locator('[data-action=review-output-adjustment]').click();
  const taxDialog=page.locator('.invoice-tax-adjustment-dialog');await taxDialog.waitFor({state:'visible'});
  assert.match(await taxDialog.innerText(),/695/);assert.match(await taxDialog.innerText(),/696/);
  assert.match(await taxDialog.innerText(),/685/);assert.match(await taxDialog.innerText(),/686/);
  assert.match(await taxDialog.innerText(),/709.600/);assert.equal(await taxDialog.locator('[data-tax-confirm]').isDisabled(),true);
  await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'tax-adjustment-review.png')});
  await taxDialog.locator('[data-tax-cancel]').click();await taxDialog.waitFor({state:'detached'});
  assert.equal(await taxRows[0].getAttribute('data-issue'),'1');
  assert.equal((await get(api)).items.find(i=>i.id===ids.tax_adjustment_invoices[0]).adjustment_review.confirmed,false);
  await taxRows[1].locator('[data-action=review-output-adjustment]').click();await taxDialog.waitFor({state:'visible'});
  await taxDialog.locator('[data-tax-only-check]').check();
  const taxSaved=page.waitForResponse(r=>r.url().endsWith('/confirm-tax'));
  await taxDialog.locator('[data-tax-confirm]').click();assert.equal((await taxSaved).status(),200);
  for(const id of ids.tax_adjustment_lines){
   await page.waitForFunction(id=>document.querySelector('#invoice-line-output-'+id)?.getAttribute('data-issue')==='0',id);
   const taxRow=page.locator('#invoice-line-output-'+id);
   assert.match(await taxRow.innerText(),/K000035/);assert.match(await taxRow.innerText(),/Không thay đổi kho/);
   assert.equal(await taxRow.locator('.invoice-draft-factor').count(),0);
  }
  const button=page.locator('[data-action=match-output-catalog-codes]');
  await page.route('**/api/invoice-workbench/output-match-codes',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Thử lỗi mạng'})}));
  await button.click();await page.waitForFunction(()=>!document.querySelector('[data-action=match-output-catalog-codes]').disabled);
  assert.equal(await cell('blank').innerText(),'Chưa ghép');await page.unroute('**/api/invoice-workbench/output-match-codes');
  const matched=page.waitForResponse(r=>r.url().endsWith('/output-match-codes'));await button.click();assert.equal((await matched).status(),200);
  await page.waitForFunction(id=>document.querySelector('#invoice-line-output-'+id+' td:nth-child(3)')?.textContent==='R1-KG',ids.blank);
  assert.equal(await cell('coded').innerText(),'R1-KG');assert.equal(await cell('alias').innerText(),'ALIAS');assert.equal(await cell('ambiguous').innerText(),'Chưa ghép');
  const after=await get(api);
  const autoReview=page.locator('#invoice-line-output-'+ids.auto_amount_review);
  assert.equal(before.lines.find(r=>r.id===ids.auto_amount_review).product_code,'');
  assert.equal(after.lines.find(r=>r.id===ids.auto_amount_review).product_code,'AUTO-REVIEW');
  assert.equal(await autoReview.getAttribute('data-issue'),'0');
  assert.match(await autoReview.innerText(),/Đã khớp mã/);
  assert.equal(await autoReview.locator('.invoice-draft-factor').count(),0);
  assert.notEqual(await autoReview.locator('td').first().evaluate(e=>getComputedStyle(e).color),'rgb(163, 35, 35)');
  for(const old of before.lines){const current=after.lines.find(r=>r.id===old.id);for(const key of ['source_item_code','source_item_name','source_unit','qty','unit_price','amount'])assert.equal(current[key],old[key]);}
  assert.equal(after.totals.line_amount,before.totals.line_amount);assert(after.items.every(i=>i.stock_status!=='posted'));
  await page.reload();await page.locator('[data-view=msmi]').click();await page.locator('#invoice-list-count').waitFor();
  assert.equal(await cell('blank').innerText(),'R1-KG');
  assert.equal(await confirmedVariant.getAttribute('data-issue'),'0');
  assert.equal(await confirmedVariant.locator('.invoice-identity-review').count(),0);
  for(const taxRow of taxRows){assert.equal(await taxRow.getAttribute('data-issue'),'0');assert.match(await taxRow.innerText(),/Đã đối chiếu điều chỉnh thuế/);}
  assert.match(await unit.innerText(),/Đã khớp mã/);assert.equal(await unit.locator('.invoice-draft-factor').count(),0);
  assert.match(await financial.innerText(),/Đã khớp mã/);
  assert.equal(await financial.getAttribute('data-issue'),'0');
  assert.equal(await unit.getAttribute('data-issue'),'0');
  const finalData=await get(api),financialLine=finalData.lines.find(l=>l.id===ids.amount_review);
  assert.equal(finalData.items.find(i=>i.id===financialLine.invoice_id).stock_status,'blocked');
  assert.match(await blocked.innerText(),/Hóa đơn cần kiểm tra/);
  await page.screenshot({path:path.join(process.env.TDP_FIXTURE_OUTPUT,'output-names.png')});
  assert.deepEqual(errors,[]);assert(writes.every(p=>p==='/api/invoice-workbench/output-match-codes'||p==='/api/invoice-workbench/output-adjustments/'+ids.tax_adjustment_invoices[1]+'/confirm-tax'));
  console.log('PASS: same name with/without source code; alias; ambiguous name blocked; network retry; mapped-code display; reload; source amounts unchanged; no stock request');
 }finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
