// Fresh synthetic browser_fixture_date_picker_server.py; no production access.
const assert = require('node:assert/strict');
const {chromium} = require(process.env.TDP_PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const browser = await chromium.launch({channel: 'chrome', headless: true});
  const page = await browser.newPage({viewport: {width: 1600, height: 1000}});
  const base = process.env.TDP_INVOICE_TEST_URL || 'http://127.0.0.1:18805';
  const errors = [], posts = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => {
    if (request.url().endsWith('/input-receipts') && request.method() === 'POST') posts.push(request.postDataJSON());
  });
  const get = async path => (await page.request.get(base + path)).json();
  const listing = () => get('/api/invoice-workbench/invoices?from=2026-08-01&to=2026-09-02');
  try {
    await page.goto(base);
    await page.evaluate(() => localStorage.setItem('tdp.invoiceWorkbenchFilters', JSON.stringify({direction: 'input', date_from: '2026-09-01', date_to: '2026-09-02', status: 'all', line_filter: 'all'})));
    await page.reload();
    await page.locator('.loading-panel').waitFor({state: 'detached'});
    await page.locator('[data-view="msmi"]').click();
    await page.locator('#invoice-list-count').waitFor();
    assert.equal(await page.locator('tr[id^="invoice-line-input-"]').count(), 0);
    await page.getByRole('button', {name: 'Còn chưa nhập', exact: true}).click();
    await page.getByRole('heading', {name: 'Hóa đơn còn chưa nhập', exact: true}).waitFor();
    assert.equal(await page.locator('tr[id^="invoice-line-input-"]').count(), 3);
    const ids = await get('/fixture/ids');
    assert.equal(await page.locator('[data-action="create-msmi-receipt"]').count(), 0);
    assert.equal(await page.getByRole('button', {name: 'Kiểm tra', exact: true}).count(), 3);
    const first = page.locator('#invoice-line-input-' + ids.line_b);
    const colors = await first.locator('td').evaluateAll(cells => cells.map(cell => ({background: getComputedStyle(cell).backgroundColor, color: getComputedStyle(cell).color})));
    assert(colors.every(c => c.background === 'rgb(255, 240, 240)' && c.color === 'rgb(163, 35, 35)'), 'Every error-row cell is red, including sticky cells');
    await first.locator('.invoice-mapping-input').fill('R1-KG');
    await page.locator('#msmiProductOptions [data-product-code="R1-KG"]').click();
    let refreshed = page.waitForResponse(r => r.url().includes('/api/invoice-workbench/invoices?'));
    await first.getByRole('button', {name: 'Lưu', exact: true}).click();
    await refreshed;
    const box = page.locator('#invoice-line-input-' + ids.line_box);
    await box.locator('.invoice-draft-factor').fill('12');
    refreshed = page.waitForResponse(r => r.url().includes('/api/invoice-workbench/invoices?'));
    await box.getByRole('button', {name: 'Lưu', exact: true}).click();
    await refreshed;
    const bulk = page.locator('[data-action="review-input-receipts"]');
    await page.getByRole('button', {name: 'Nhập kho 1 hóa đơn', exact: true}).waitFor();
    assert(!(await first.innerText()).includes('Đã đủ mã · Chưa nhập kho'));
    await first.getByRole('button', {name: 'Kiểm tra', exact: true}).click();
    await page.locator('.invoice-receipt-summary-dialog').waitFor();
    await page.locator('.invoice-receipt-summary-dialog button').click();
    const before = await listing();
    const dialog = page.locator('.receipt-review-dialog');
    await bulk.click();
    await dialog.locator('.receipt-confirm').waitFor();
    assert.equal(await dialog.locator('.receipt-choice').count(), 1);
    assert.match(await dialog.innerText(), /1 hóa đơn chưa thể nhập/);
    assert.match(await dialog.innerText(), /C26TST \/ 3/);
    await dialog.locator('.receipt-cancel').click();
    assert.equal(posts.length, 0);
    assert.deepEqual((await listing()).lines, before.lines);
    await bulk.click();
    await dialog.locator('.receipt-confirm').waitFor();
    if (process.env.TDP_PENDING_SCREENSHOT) await page.screenshot({path: process.env.TDP_PENDING_SCREENSHOT});
    refreshed = page.waitForResponse(r => r.url().includes('/api/invoice-workbench/invoices?'));
    await dialog.locator('.receipt-confirm').click();
    await refreshed;
    await first.waitFor({state: 'detached'});
    assert.equal(posts.length, 1);
    assert.deepEqual(posts[0].items.map(r => r.id), [ids.input_ids['2']]);
    assert.equal(await page.locator('tr[id^="invoice-line-input-"]').count(), 1);
    await page.reload();
    await page.locator('.loading-panel').waitFor({state: 'detached'});
    await page.locator('[data-view="msmi"]').click();
    await page.getByRole('heading', {name: 'Hóa đơn còn chưa nhập', exact: true}).waitFor();
    assert.equal(await page.locator('tr[id^="invoice-line-input-"]').count(), 1);
    await page.getByRole('button', {name: 'Xem theo ngày', exact: true}).click();
    await page.getByRole('heading', {name: 'Hóa đơn trong khoảng ngày đã chọn', exact: true}).waitFor();
    assert.equal(await page.locator('tr[id^="invoice-line-input-"]').count(), 0);
    assert.deepEqual(errors, []);
    console.log('PASS: old pending visible, compact actions, all error cells red, map/check/bulk confirmation, cancel read-only, blocked invoice retained, pending persists after reload, date scope restored');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
