const assert=require('node:assert/strict');
const {chromium}=require(process.env.TDP_PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const base=process.env.TDP_STOCK_TEST_URL || 'http://127.0.0.1:18920';
  const errors=[],writes=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(['POST','PUT','DELETE'].includes(r.method()))writes.push(r.url());});
  const get=async p=>(await page.request.get(base+p)).json();
  const dialog=page.locator('.receipt-review-dialog');
  try {
    await page.addInitScript(()=>localStorage.setItem('tdp.invoiceWorkbenchFilters',JSON.stringify({direction:'output',date_from:'2026-08-01',date_to:'2026-08-31',status:'all',line_filter:'all'})));
    await page.goto(base);await page.locator('.loading-panel').waitFor({state:'detached'});
    await page.locator('[data-view="msmi"]').click();await page.locator('#invoice-list-count').waitFor();
    const before=await get('/fixture/digest');
    assert.equal(await page.getByRole('columnheader',{name:'Thao tác cả hóa đơn'}).count(),0);
    assert.equal(await page.locator('.invoice-draft-factor').count(),0);
    await page.getByRole('button',{name:'Ghi xuất kho',exact:true}).click();
    await dialog.locator('.receipt-confirm').waitFor();
    assert.match(await dialog.innerText(),/không gửi hoặc phát hành hóa đơn/);
    assert.equal(await dialog.locator('.receipt-choice').count(),1);
    assert.match(await dialog.innerText(),/thiếu 4/);
    await dialog.locator('.receipt-cancel').click();
    assert.deepEqual(await get('/fixture/digest'),before,'Review and cancel must not write');
    // A failed request stays open and can be retried with the reviewed selection.
    await page.route('**/api/invoice-workbench/output-postings',async r=>{
      if(r.request().method()==='POST') await r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Lỗi mạng kiểm thử'})});else await r.continue();
    });
    await page.getByRole('button',{name:'Ghi xuất kho',exact:true}).click();
    await dialog.locator('.receipt-confirm').click();
    await dialog.getByText(/Lỗi mạng kiểm thử/).waitFor();
    await page.unroute('**/api/invoice-workbench/output-postings');
    await dialog.locator('.receipt-confirm').click();await dialog.waitFor({state:'detached'});
    await page.getByRole('heading',{name:'Hóa đơn trong khoảng ngày đã chọn',exact:true}).waitFor();
    assert.equal(await page.locator('[data-action=toggle-pending-invoices]').getAttribute('aria-pressed'),'false');
    let pending=await get('/api/invoice-workbench/invoices?invoice_type=output&from=2026-09-01&to=2026-09-02&scope=pending');
    assert.equal(pending.items.length,2);assert(!pending.items.some(r=>r.invoice_number==='90'));
    await page.screenshot({path:'tmp/stock-output-workflow.png'});
    await page.getByRole('button',{name:'Tạo file đưa lên M-Invoice',exact:true}).click();
    await page.getByRole('heading',{name:'File đưa lên M-Invoice',exact:true}).waitFor();
    assert.match(await page.locator('#content').innerText(),/Tải ZIP về máy, giải nén/);
    await page.getByRole('button',{name:'Cần duyệt đơn trước',exact:true}).waitFor();
    // Month actions remain out of the compact report landing until opened.
    await page.locator('[data-view="inventory"]').click();
    assert.equal(await page.locator('.inventory-month-close').count(),0);
    await page.getByRole('button',{name:'Chuyển tồn sang tháng sau',exact:true}).click();
    const close=page.locator('.inventory-close-dialog');
    await close.locator('[data-action="close-inventory-month"]').waitFor();
    assert.equal(await close.locator('#inventoryClosePeriod').inputValue(),'2026-08');
    assert.match(await close.innerText(),/hóa đơn đầu ra chưa ghi kho/);
    const snapshot=await get('/fixture/digest');
    await close.locator('[data-action="close-inventory-month"]').click();
    assert.match(await page.locator('#toast').innerText(),/Nhập tên người xác nhận/);
    await close.locator('#inventoryCloseActor').fill('QA');
    page.once('dialog',d=>d.dismiss());
    await close.locator('[data-action="close-inventory-month"]').click();
    assert.deepEqual(await get('/fixture/digest'),snapshot);
    const preview=await get('/api/inventory/month-close/preview?period=2026-08');
    page.once('dialog',d=>d.accept());
    await close.locator('[data-action="close-inventory-month"]').click();
    await close.locator('[data-action="reopen-inventory-month"]:enabled').waitFor();
    assert.match(await close.innerText(),/Đã chốt/);
    const september=await get('/api/invoice-valuation?from=2026-09-01&to=2026-09-30');
    assert.equal(september.items.find(r=>r.product_code==='R1-KG').opening_qty,preview.total_qty);
    await close.screenshot({path:'tmp/stock-month-workflow.png'});
    page.once('dialog',d=>d.accept());
    await close.locator('[data-action="reopen-inventory-month"]').click();
    await close.locator('[data-action="close-inventory-month"]:enabled').waitFor();
    page.once('dialog',d=>d.accept());
    await close.locator('[data-action="close-inventory-month"]').click();
    await close.locator('[data-action="reopen-inventory-month"]:enabled').waitFor();
    const repeated=await get('/api/invoice-valuation?from=2026-09-01&to=2026-09-30');
    assert.equal(repeated.items.find(r=>r.product_code==='R1-KG').opening_qty,preview.total_qty);
    await close.locator('.close-period-dialog').click();
    // Exact customer example, including visible native-validation failure and whole-catalog search.
    await page.locator('[data-view="settings"]').click();
    await page.getByRole('button',{name:'Thêm mã hàng',exact:true}).click();
    const catalog=page.locator('.catalog-product-dialog');
    await catalog.locator('[name="code"]').fill('HT00245');await catalog.locator('[name="name"]').fill('Hạt bí xanh hộp 480g');
    await catalog.locator('[type="submit"]').click();await catalog.getByText(/Chưa lưu. Cần nhập đủ/).waitFor();
    await catalog.locator('[name="unit"]').fill('Hộp');await catalog.locator('[name="tax"]').selectOption('0.08');
    await catalog.locator('[type="submit"]').click();await catalog.waitFor({state:'detached'});
    await page.locator('#catalogProducts').getByText('HT00245',{exact:true}).waitFor();
    assert.equal((await get('/api/catalog/products')).catalog_total,1256);
    await page.locator('#catalogSearchForm input').fill('hat bi xanh hop');await page.locator('#catalogSearchForm button').click();
    await page.locator('#catalogProducts').getByText('HT00245',{exact:true}).waitFor();
    await page.reload();await page.locator('.loading-panel').waitFor({state:'detached'});
    assert.equal((await get('/api/catalog/products?q=HT00245')).items[0].code,'HT00245');
    assert.deepEqual(errors,[]);
    console.log('PASS stock workflow: read-only preview/cancel, combined stock, network retry, output/pending, M-Invoice file path, month confirmation/reopen/reclose, catalog 1255→1256 and global accentless search');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
