// Run with browser_fixture_date_picker_server.py (synthetic data only).
const assert = require('node:assert/strict');
const {chromium} = require(process.env.TDP_PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const browser = await chromium.launch({channel:'chrome', headless:true});
  const page = await browser.newPage({viewport:{width:1440, height:1000}});
  const base = process.env.TDP_INVOICE_TEST_URL || 'http://127.0.0.1:18805';
  const errors = [], writes = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().endsWith('/api/catalog/products')) writes.push(request.postDataJSON()); });
  try {
    await page.addInitScript(() => localStorage.setItem('tdp.invoiceWorkbenchFilters', JSON.stringify({direction:'input',date_from:'2026-08-01',date_to:'2026-08-31',status:'all',line_filter:'all'})));
    await page.goto(base);
    await page.locator('.loading-panel').waitFor({state:'detached'});
    await page.locator('[data-view="settings"]').click();
    await page.getByRole('heading', {name:'Danh mục hàng hóa', exact:true}).waitFor();
    assert.equal(await page.locator('#outgoingNameForm').count(), 0);
    assert.equal(await page.getByRole('button', {name:'Nạp từ Excel', exact:true}).count(), 1);
    const trigger = page.getByRole('button', {name:'Thêm mã hàng', exact:true});
    const dialog = page.locator('.catalog-product-dialog');
    await trigger.click();
    await dialog.waitFor();
    assert(await dialog.locator('[name="code"]').evaluate(e => e === document.activeElement));
    assert.equal(await dialog.locator('[name="tax"] option').count(), 7);
    await page.keyboard.press('Escape');
    await dialog.waitFor({state:'detached'});
    assert.equal(writes.length, 0);
    await trigger.click();
    await dialog.getByRole('button', {name:'Lưu mã hàng', exact:true}).click();
    assert.equal(writes.length, 0, 'Required empty fields prevent submission');
    await dialog.locator('[name="code"]').fill('r1-kg');
    await dialog.locator('[name="name"]').fill('Tên không được ghi đè');
    await dialog.locator('[name="unit"]').fill('Cái');
    await dialog.locator('[name="tax"]').selectOption('0.08');
    await dialog.getByRole('button', {name:'Lưu mã hàng', exact:true}).click();
    await dialog.locator('.catalog-product-error').filter({hasText:'đã có trong danh mục'}).waitFor();
    assert.equal(await dialog.locator('[name="name"]').inputValue(), 'Tên không được ghi đè');
    await dialog.locator('[name="code"]').fill('new-ui-003');
    await dialog.locator('[name="name"]').fill('Đậu phụ chiên kiểm thử');
    await dialog.locator('[name="invoice_name"]').fill('Đậu phụ vàng');
    if (process.env.TDP_CATALOG_SCREENSHOT) await dialog.screenshot({path:process.env.TDP_CATALOG_SCREENSHOT});
    const saved = page.waitForResponse(r => r.url().endsWith('/api/catalog/products'));
    await dialog.getByRole('button', {name:'Lưu mã hàng', exact:true}).click();
    assert.equal((await saved).status(), 201);
    await dialog.waitFor({state:'detached'});
    const edit = page.locator('#catalogProducts [data-code="NEW-UI-003"]');
    await edit.waitFor();
    assert.match(await page.locator('#catalogProducts').innerText(), /Đậu phụ vàng/);
    await edit.click();
    await dialog.waitFor();
    assert.equal(await dialog.locator('[name="invoice_name"]').inputValue(), 'Đậu phụ vàng');
    assert(await dialog.locator('[name="code"]').evaluate(e => e.readOnly));
    await dialog.locator('[name="invoice_name"]').fill('Đậu phụ chiên hóa đơn');
    await dialog.getByRole('button', {name:'Lưu mã hàng', exact:true}).click();
    await dialog.waitFor({state:'detached'});
    await page.locator('#catalogProducts').getByText('Đậu phụ chiên hóa đơn', {exact:true}).waitFor();
    if (process.env.TDP_CATALOG_SCREENSHOT) await page.locator('.card').filter({has:page.getByRole('heading', {name:'Danh mục hàng hóa', exact:true})}).screenshot({path:process.env.TDP_CATALOG_SCREENSHOT.replace('.png','-list.png')});
    const result = await (await page.request.get(base + '/api/products/search?q=NEW-UI-003')).json();
    assert.equal(result.items[0].code, 'NEW-UI-003');
    assert.equal(result.items[0].unit, 'Cái');
    assert.equal(result.items[0].tax, '0.08');
    assert.equal(result.items[0].invoice_name, 'Đậu phụ chiên hóa đơn');
    await page.locator('[data-view="msmi"]').click();
    await page.locator('#invoice-list-count').waitFor();
    const ids = await (await page.request.get(base + '/fixture/ids')).json();
    const row = page.locator('#invoice-line-input-' + ids.line_b);
    await row.locator('.invoice-mapping-input').fill('NEW-UI-003');
    await page.locator('#msmiProductOptions [data-product-code="NEW-UI-003"]').click();
    assert.equal(await row.locator('.invoice-mapping-input').getAttribute('data-selected-code'), 'NEW-UI-003');
    assert.match(await row.locator('.invoice-draft-factor').getAttribute('title'), /Cái/);
    assert.deepEqual(errors, []);
    console.log('PASS: unified catalog, create/edit invoice name, cancel/required fields, duplicate protected, refreshed catalog, new product selectable with correct unit in invoice mapping');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
