const assert = require('node:assert/strict');
const fs = require('node:fs');
const {chromium} = require(process.env.TDP_PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({channel:'chrome',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const base = process.env.TDP_AMOUNT_TEST_URL || 'http://127.0.0.1:18855';
  const errors=[], writes=[];
  page.on('pageerror', e=>errors.push(e.message));
  page.on('request', r=>{if(r.method()==='POST' && r.url().includes('/api/')) writes.push(r.url());});
  const get = async path => (await page.request.get(base+path)).json();
  const modal=page.locator('.invoice-amount-dialog');
  const idle=()=>page.waitForFunction(()=>document.querySelector('.invoice-amount-dialog')?.getAttribute('aria-busy')==='false');
  const open=async()=>{await page.locator('[data-action="review-invoice-amount"]').click();await idle();};
  try {
    await page.addInitScript(()=>localStorage.setItem('tdp.invoiceWorkbenchFilters',JSON.stringify({direction:'output',date_from:'2026-08-01',date_to:'2026-08-31',status:'all',line_filter:'all'})));
    await page.goto(base);await page.locator('.loading-panel').waitFor({state:'detached'});
    await page.locator('[data-view="msmi"]').click();await page.locator('#invoice-list-count').waitFor();
    await page.locator('.invoice-amount-reviews summary').click();
    const before=await get('/fixture/snapshot');
    await open();assert.match(await modal.innerText(),/Chưa xác định được dòng thiếu/);
    assert.match(await modal.innerText(),/Hàng kiểm thử <an toàn>/);
    assert(await modal.locator('[data-apply]').isVisible());assert(await modal.locator('[data-apply]').isDisabled());
    await modal.locator('[data-recheck]').click();await idle();
    assert.match(await modal.innerText(),/Vừa kiểm tra lại từ M-Invoice/);
    assert(await modal.locator('[data-apply]').isDisabled());
    const downloadEvent=page.waitForEvent('download');await modal.locator('[data-download]').click();
    const download=await downloadEvent;await download.saveAs('amount-support.xlsx');await idle();
    assert(fs.statSync('amount-support.xlsx').size>4000);
    await modal.screenshot({path:'amount-review-unresolved.png'});
    await page.keyboard.press('Escape');await modal.waitFor({state:'detached'});
    assert.deepEqual(await get('/fixture/snapshot'),before);assert.equal(writes.length,0);
    await open();
    await page.route('**/amount-review?fresh=1', r=>r.fulfill({status:502,contentType:'application/json',body:JSON.stringify({ok:false,error:'Mất kết nối thử nghiệm'})}));
    await modal.locator('[data-recheck]').click();await idle();
    assert.match(await modal.locator('[data-error]').innerText(),/Mất kết nối/);
    assert(await modal.locator('[data-download]').isEnabled());assert(await modal.locator('[data-apply]').isDisabled());
    await page.unroute('**/amount-review?fresh=1');
    await page.request.post(base+'/fixture/fix-source');
    await modal.locator('[data-recheck]').click();await idle();
    assert(await modal.locator('[data-apply]').isEnabled());assert.match(await modal.innerText(),/So với lần tải trước/);
    assert.deepEqual(await get('/fixture/snapshot'),before);
    await modal.screenshot({path:'amount-review-ready.png'});
    // Close after a good check still does not save anything.
    await modal.locator('[data-close]').click();await open();
    assert(await modal.locator('[data-apply]').isDisabled());
    await modal.locator('[data-recheck]').click();await idle();
    const applied=page.waitForResponse(r=>r.url().endsWith('/amount-review/apply'));
    await modal.locator('[data-apply]').click();assert.equal((await applied).status(),200);await idle();
    assert.match(await modal.innerText(),/Đã cập nhật hóa đơn/);
    await modal.locator('[data-close]').click();
    const after=await get('/fixture/snapshot');
    for(const table of ['invoice_line_mappings','invoice_inventory_ledger','inventory_transactions','orders']) assert.equal(after[table],before[table],table);
    assert.notEqual(after.outgoing_source_invoices,before.outgoing_source_invoices);
    assert.equal(await page.locator('.invoice-amount-reviews').count(),0);
    assert.equal(writes.length,1);assert.deepEqual(errors,[]);
    console.log(JSON.stringify({ok:true,writes:writes.length,errors}));
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
