'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');

async function main() {
  const page = await fetch('http://127.0.0.1:19313/json/new?about:blank', {method:'PUT'}).then(r => r.json());
  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let seq=0; const pending=new Map(), errors=[];
  ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails);if(pending.has(msg.id)){const [yes,no]=pending.get(msg.id);pending.delete(msg.id);msg.error?no(Error(msg.error.message)):yes(msg.result);}};
  const call=(method,params={})=>new Promise((yes,no)=>{const id=++seq;pending.set(id,[yes,no]);ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const wait=async expression=>{const until=Date.now()+20000;while(Date.now()<until){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timeout: '+expression);};
  const click=async selector=>{await wait(`document.querySelector(${JSON.stringify(selector)})`);await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);};
  const set=async(selector,value,type='input')=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event(${JSON.stringify(type)},{bubbles:true}));})()`);
  const visibleRows=()=>evaluate(`document.querySelectorAll('[data-order-row]:not([hidden])').length`);
  try {
    await call('Runtime.enable');await call('Page.enable');
    await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:'D:\\TDP_ROUND2\\downloads'});
    await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
    await call('Page.addScriptToEvaluateOnNewDocument',{source:`window.confirm=()=>true;window.__copyFail=true;window.__copied=0;window.__imageText=[];Object.defineProperty(navigator,'clipboard',{value:{write:async()=>{if(window.__copyFail)throw Error('clipboard blocked');window.__copied++;}}});const fill=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){window.__imageText.push(text);return fill.call(this,text,...args);};`});
    await call('Page.navigate',{url:'http://127.0.0.1:18803'});
    await wait(`document.querySelector('[data-view="orders"]')&&!document.querySelector('.loading-panel')`);
    await click('[data-view="orders"]');
    await wait(`document.querySelectorAll('[data-order-row]').length===65`);
    assert.equal(await visibleRows(),65);
    assert.match(await evaluate(`document.querySelector('#orderTable').textContent`),/0,855/);
    await set('.quick-sell-price','1500');
    await set('#orderIssueFilter','error','change');assert.equal(await visibleRows(),2);
    assert.match(await evaluate(`document.querySelector('#orderVisibleTotals').textContent`),/2 \/ 65/);
    await set('#orderIssueFilter','warning','change');assert.equal(await visibleRows(),2);
    assert.equal(await evaluate(`document.querySelectorAll('[data-order-row].row-error:not([hidden])').length`),0);
    await set('#orderIssueFilter','all','change');
    await set('#orderSearch','P1');assert.equal(await visibleRows(),32);
    await set('#orderSearch','NO_MATCH');assert.equal(await visibleRows(),0);
    assert.match(await evaluate(`document.querySelector('#orderVisibleTotals').textContent`),/0 \/ 65/);
    await set('#orderSearch','');assert.equal(await visibleRows(),65);
    assert.equal(await evaluate(`document.querySelector('.quick-sell-price').value`),'1500');
    await click('[data-action="first-order-error"]');assert.equal(await visibleRows(),2);
    assert.equal(await evaluate(`document.activeElement.dataset.action`),'edit-order');
    await set('#orderIssueFilter','all','change');
    const sticky=await evaluate(`(()=>{const box=document.querySelector('#orderTable');box.scrollTop=500;box.scrollLeft=200;const th=box.querySelector('th');return {position:getComputedStyle(th).position,top:Math.abs(th.getBoundingClientRect().top-box.getBoundingClientRect().top),horizontal:box.scrollWidth>box.clientWidth};})()`);
    assert.equal(sticky.position,'sticky');assert.ok(sticky.top<4);assert.ok(sticky.horizontal);
    await click('[data-action="bulk-edit-orders"]');
    assert.equal(await evaluate(`document.querySelector('[data-bulk-field="qty"]').step`),'any');
    assert.equal(await evaluate(`getComputedStyle(document.querySelector('.bulk-grid th')).color`),'rgb(255, 255, 255)');
    await click('[data-action="close-modal"]');
    await click('[data-view="purchases"]');
    await wait(`document.querySelectorAll('.supplier-order-card').length===2`);
    await click('.supplier-lines summary');
    assert.equal(await evaluate(`document.querySelector('.supplier-lines tbody').rows.length`),40);
    await click('[data-action="copy-supplier-image"]');
    await wait(`document.querySelector('#toast').textContent.includes('chưa đánh dấu')`);
    assert.equal(await evaluate(`document.querySelectorAll('.supplier-order-card.is-ordered').length`),0);
    await evaluate('window.__copyFail=false;window.__imageText=[]');
    await click('[data-action="copy-supplier-image"]');
    await wait(`document.querySelectorAll('.supplier-order-card.is-ordered').length===1`);
    assert.equal(await evaluate(`document.querySelector('.supplier-order-list').lastElementChild.dataset.supplierKey`),'s1');
    assert.ok(await evaluate(`window.__imageText.includes('K1') && window.__imageText.includes('K2')`),'Copied image covers all kitchens of supplier');
    await click('[data-action="set-supplier-order-status"]');
    await wait(`document.querySelector('.supplier-order-card.is-reopened')`);
    fs.writeFileSync('D:/TDP_ROUND2/suppliers-browser.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
    await click('[data-view="physical"]');
    await wait(`document.querySelector('#physicalFilterForm')`);
    assert.match(await evaluate(`document.querySelector('#content').textContent`),/Chưa khai tồn đầu/);
    await click('[data-action="physical-entry"][data-kind="opening"][data-code="P1"]');
    await set('#physicalStockForm [name="work_date"]','2026-09-05','change');
    await set('#physicalStockForm [name="qty"]','100');
    await set('#physicalStockForm [name="unit_cost"]','1000');
    await set('#physicalStockForm [name="actor"]','Kiểm thử');
    await set('#physicalStockForm [name="reason"]','Đếm hàng đầu ngày');
    await click('#physicalStockForm [type="submit"]');
    await wait(`!document.querySelector('#physicalStockForm') && document.querySelector('#physicalFilterForm')`);
    const stock=await evaluate(`fetch('/api/physical-stock').then(r=>r.json())`);
    assert.equal(stock.items.find(i=>i.product_code==='P1').balance_qty,68);
    await click('[data-action="physical-entry"][data-kind="movement"][data-code="P1"]');
    await set('#physicalStockForm [name="work_date"]','2026-09-05','change');
    await set('#physicalStockForm [name="qty"]','2.5');
    await set('#physicalStockForm [name="unit_cost"]','1000');
    await set('#physicalStockForm [name="actor"]','Kiểm thử');
    await set('#physicalStockForm [name="reason"]','Nhập thực tế');
    await click('#physicalStockForm [type="submit"]');
    await wait(`!document.querySelector('#physicalStockForm')`);
    assert.equal(await evaluate(`fetch('/api/physical-stock').then(r=>r.json()).then(p=>p.items.find(i=>i.product_code==='P1').balance_qty)`),70.5);
    fs.writeFileSync('D:/TDP_ROUND2/physical-stock-browser.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
    await click('[data-action="physical-source-order"]');
    await wait(`document.querySelector('#orderTable')`);
    const settleId=await evaluate(`document.querySelector('[data-order-row]:not(.row-error) [data-action="settle-physical-order"]').dataset.id`);
    await click(`[data-action="settle-physical-order"][data-id="${settleId}"]`);
    await wait(`document.querySelector('[data-action="settle-physical-order"][data-id="${settleId}"]').textContent.includes('Đã giao')`);
    await click(`[data-action="settle-physical-order"][data-id="${settleId}"]`);
    await wait(`document.querySelector('[data-action="settle-physical-order"][data-id="${settleId}"]').textContent.includes('Chốt lượng')`);
    await click('[data-view="deliveries"]');
    await wait(`document.querySelector('#pageTitle').textContent.includes('Phiếu giao')`);
    await click('[data-view="orders"]');
    for(const width of [1440,1024]){
      await call('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});
      assert.ok(await evaluate('document.documentElement.scrollWidth<=window.innerWidth+1'),'No page overflow at '+width);
    }
    fs.writeFileSync('D:/TDP_ROUND2/orders-browser.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
    assert.deepEqual(errors,[]);
    console.log('ROUND2_BROWSER_OK: 65 rows, filters/totals, draft preserved, sticky headers, all-NCC image, clipboard safety, opening/receipt/source trace, 1024px.');
  } finally {ws.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
